name: Helm Lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited, labeled]
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: self-hosted
    timeout-minutes: 5
    env:
      RUNNER_TOOL_CACHE: /tmp
      AGENT_TOOLSDIRECTORY: /tmp
      RUN_TOOL_CACHE: /tmp
    steps:
      - name: Checkout
        uses: https://git.open.engineering/oeng/checkout-action@main

      - name: Add dependency chart repos
        run: |
          helm repo add git.open.engineering \
            https://git.open.engineering/api/packages/oeng/helm
          helm repo add percona \
            https://percona.github.io/percona-helm-charts/

      - name: Run chart-testing (lint)
        id: lint
        run: |
          ct lint \
          --target-branch ${{ env.FORGEJO_HEAD_REF }} \
          --charts charts/coturn

