name: Check PR Labels

on:
  pull_request:
    types: [opened, synchronize, edited, labeled]

jobs:
  check-pr-labels:
    uses: oeng/reusable-workflows/.forgejo/workflows/check-pr-labels.yaml@main
    with:
      default_patch: false
      skip_checks: ""
