name: Release Chart

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'charts/coturn/Chart.yaml'

jobs:
  harbor:
    uses: oeng/reusable-workflows/.forgejo/workflows/publish-charts.yaml@main
    with:
      harbor_url: harbor.open.engineering
      harbor_project: charts
      force: false
      chart_dir: charts
      chart: coturn
    secrets:
      harbor_user: ${{ secrets.HARBOR_USERNAME }}
      harbor_token: ${{ secrets.HARBOR_TOKEN }}

  forgejo:
    uses: oeng/reusable-workflows/.forgejo/workflows/publish-charts.yaml@main
    with:
      forgejo_url: https://git.open.engineering
      owner: oeng
      repo: coturn-chart
      force: false
      chart_dir: charts
      chart: coturn
      release: true
    secrets:
      forgejo_api_token: ${{ secrets.FORGE_TOKEN }}

  codeberg:
    uses: oeng/reusable-workflows/.forgejo/workflows/publish-charts.yaml@main
    with:
      owner: open-engineering
      repo: coturn-chart
      force: false
      chart_dir: charts
      chart: coturn
      codeberg: true
      release: false
    secrets:
      codeberg_token: ${{ secrets.CODEBERG_TOKEN }}
