name: Renovate
on:
  workflow_dispatch:
  schedule:
  # This should be every hour at the 55th minute
  - cron: '55 * * * *'
  push:
    branches:
      - main
    paths:
      - ".forgejo/renovate-config.json"
      - ".forgejo/workflows/renovate.yml"
      - "renovate.json"
      - "scripts/**"
jobs:
  renovate:
    uses: small-hack/reusable-workflows/.forgejo/workflows/renovate.yaml@main
    secrets: inherit
