name: Renovate
on:
  workflow_dispatch:
  schedule:
  # This should be once a day at midnight
  - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - ".forgejo/renovate-config.json"
      - ".forgejo/workflows/renovate.yml"
      - "renovate.json"
      - "scripts/**"
jobs:
  renovate:
    uses: oeng/reusable-workflows/.forgejo/workflows/renovate.yaml@main
    secrets: inherit
